@startuml
' Generated: 1767242491565
skinparam shadowing false
skinparam activity {
  BackgroundColor #E6E6FA
  BorderColor #6A5ACD
  ArrowColor #483D8B
  StartColor #4CAF50
  EndColor #E53935
  FontSize 11
}
skinparam partition {
  BackgroundColor #F0F0F0
  BorderColor #999999
  FontSize 11
  BorderThickness 2
}
skinparam activityEndColor #E53935
skinparam dpi 300
start
:<&cloud> **HTTP Receiver**\nhttpEventSource;
fork
->
:<&file> **Log**\nlog;
->
:<&cloud> **REST Dispatch and Reply**\nRestAdapter;
fork again
-[#483D8B]->[testingxpath]
:<&cog> **createOrderService**\nsubprocess;
end fork
->
:<&file> **Log-1**\nlog;
->
stop
@enduml