@startuml
' Generated: 1767222988085
skinparam shadowing false
skinparam activity {
  BackgroundColor #E6E6FA
  BorderColor #6A5ACD
  ArrowColor #483D8B
  StartColor #4CAF50
  EndColor #E53935
  FontSize 11
}
skinparam partition {
  BackgroundColor #F0F0F0
  BorderColor #999999
  FontSize 11
  BorderThickness 2
}
skinparam activityEndColor #E53935
skinparam dpi 300
start
:<&file> **File Poller**\nFileEventSourceResource;
->
:<&key> **GetVariable**\ngetSharedVariable;
->
:<&key> **SetVariable**\nsetSharedVariable;
->
:<&file> **Log**\nlog;
->
:<&puzzle-piece> **Parse Data**\nParse;
->
:<&cog> **createOrder**\nsubprocess;
->
:<&file> **Copy File**\nFileCopy;
->
:<&file> **Rename File**\nFileRename;
->
:Null;
fork
-[#483D8B]-> "1=2"
:<&file> **Remove File**\nFileRemove;
->
:<&file> **List Files**\nListFiles;
->
fork again
->
:<&clock> **Sleep**\nsleep;
->
:<&file> **Write File**\nFileWrite;
->
end fork
:<&file> **Log-1**\nlog;
->
stop
@enduml