@startuml
' Generated: 1767242488820
skinparam shadowing false
skinparam activity {
  BackgroundColor #E6E6FA
  BorderColor #6A5ACD
  ArrowColor #483D8B
  StartColor #4CAF50
  EndColor #E53935
  FontSize 11
}
skinparam partition {
  BackgroundColor #F0F0F0
  BorderColor #999999
  FontSize 11
  BorderThickness 2
}
skinparam activityEndColor #E53935
skinparam dpi 300
start
:<&code> **Java Event Source**\nJavaEventSource;
fork
->
:<&code> **Java Method**\nJavaMethod;
->
fork
-[#483D8B]->[javaflag]
:<&code> **Java Code**\njava;
fork again
-[#483D8B]->[Otherwise]
:<&file> **Log**\nlog;
fork again
-[#483D8B]->[fileflag]
:<&file> **Write File**\nFileWrite;
end fork
fork again
-[#483D8B]->[parseflag]
:<&puzzle-piece> **Java To XML**\nJavaToXml;
fork again
->
:<&puzzle-piece> **XML To Java**\nXmlToJava;
fork again
-[#483D8B]->[xpathflag]
fork
-[#483D8B]->[javaflag]
:<&code> **Java Code**\njava;
fork again
-[#483D8B]->[Otherwise]
:<&file> **Log**\nlog;
fork again
-[#483D8B]->[fileflag]
:<&file> **Write File**\nFileWrite;
end fork
end fork
->
stop
@enduml