@startuml
' Generated: 1767242490226
skinparam shadowing false
skinparam activity {
  BackgroundColor #E6E6FA
  BorderColor #6A5ACD
  ArrowColor #483D8B
  StartColor #4CAF50
  EndColor #E53935
  FontSize 11
}
skinparam partition {
  BackgroundColor #F0F0F0
  BorderColor #999999
  FontSize 11
  BorderThickness 2
}
skinparam activityEndColor #E53935
skinparam dpi 300
start
:<&puzzle-piece> **onStartup**\nonStartup;
fork
->
:<&key> **SetVariable_counter**\nsetSharedVariable;
fork again
->
:<&key> **SetVariable_timestamp**\nsetSharedVariable;
end fork
->
:<&file> **Log**\nlog;
->
stop
@enduml